### ISSUE TITLE
Could add more functions such as Socket

### ISSUE THREAD

**Issue by sannnyu** [naihaishy/SerialPort-Communication#2]
Recently , I am thinking of this app,which could have more function.We could merge some other's code or functions. Serial Communication is an old tech, and in the new ways of commuciation ,there are bluetooth and wifi ...(Narrow Band may be complex for me) . If you get some good idea to improve this app, I'd like to give you a hand   ; )

**Comment by naihaishy** [comment]
谢谢你的建议，我有时间学习一下，然后尝试实现一下目前常用的几种设备通信方式，不过我是新手，可能有些难度，尽力试试吧~
